# Generated by Django 4.0.3 on 2023-11-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
            ],
        ),
    ]
