# Generated by Django 4.0.3 on 2023-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lunch_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
