# Generated by Django 4.0.3 on 2023-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menu_lunch_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='breakfast_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
