# Generated by Django 4.0.3 on 2023-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menu_breakfast_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='breakfast_sold_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_sold_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
