# Generated by Django 4.0.3 on 2023-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menu_breakfast_sold_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='breakfast_sold_out_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch_sold_out_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
